# NUMPY

In [1]:
import numpy as np

In [3]:
#create numpy array

arr1=np.array([])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
#create 1-D array

arr1d=np.array([0,1,2,3])
arr1d


array([0, 1, 2, 3])

In [6]:
#create 2-d array

arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#ndmin

arrndim=np.array([],ndmin=4)

In [9]:
arrndim

array([], shape=(1, 1, 1, 0), dtype=float64)

In [12]:
#dtype
arrdtype=np.array([],dtype=float, ndmin=3)
arrdtype

array([], shape=(1, 1, 0), dtype=float64)

In [13]:
# #supported data types
# bool_
# int_
# int8
# int6
# int32
#uint32
#float16



In [20]:
#3-d array
arr3d=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
arr3d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [15]:
#0-d array
z=np.array(12)
z

array(12)

In [21]:
#to check the dimension

arr3d.ndim

4

In [18]:
arr2d.ndim

2

In [23]:
 #array Indexing
    
a1=np.array([9,8,7,6,5,4,3,2,1])
a1[3]

6

In [24]:
arr2d[1,2]

6

In [25]:

a3d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a3d

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [26]:
a3d[0,1,2]

6

In [27]:
a3d[-1,-2,-1]

6

In [33]:
a3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
a3d[-1,-2]

array([4, 5, 6])

In [31]:
a3d[-1,-2,-1]

6

In [35]:
#slicing
#[start:end]
#[start:end:step]

a3d[-1, 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a3d[0,0,1:2]

array([2])

In [38]:
a3=np.array([[3,4,5],[6,7,8],[1,2,3],[9,1,10]])
a3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 1,  2,  3],
       [ 9,  1, 10]])

In [40]:
a3[-2, 1:3]

array([2, 3])

In [42]:
# #np data types
# i - integer
# b - boolean
# u - unsigned int
# f - float
# c - complex float
# m - timedelta
# M - datatime
# O - object
# S - string
# U - unicode string
# V - void (memory fix chunk)


In [44]:
b1=np.array([1,2,3,4,5], dtype='i')
b1.dtype

dtype('int32')

In [49]:
 b3= np.array(["arm", "shyam", "haribam"], dtype="S")
b3.dtype

dtype('S7')

In [51]:
#astype
b3.astype("U")

array(['arm', 'shyam', 'haribam'], dtype='<U7')

# copy and view

#Assignment-2

Deep copy vs Swallo copy in python

copy vs view in numpy

In [52]:
#copy and View 

b3

array([b'arm', b'shyam', b'haribam'], dtype='|S7')

In [54]:
c3=b3.copy()
c3

array([b'arm', b'shyam', b'haribam'], dtype='|S7')

In [55]:
#view

d3=b3.view()

In [56]:
#difference between view and array

arr1=np.array([2,3,4,5,6,7])

In [57]:
arr2=arr1.copy()
arr3=arr1.view()

In [58]:
arr2

array([2, 3, 4, 5, 6, 7])

In [59]:
arr3

array([2, 3, 4, 5, 6, 7])

In [60]:
#shape
arr3.shape

(6,)

In [61]:
arr3d.shape

(1, 1, 4, 3)

In [62]:
arr2d.shape

(2, 3)

In [63]:
nj=np.array([],ndmin=5)

In [64]:
nj.shape

(1, 1, 1, 1, 0)

In [65]:
#reshaping
a1

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [66]:
a1.reshape(3,3)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [67]:
aa=np.array([9, 8, 7, 6, 5, 4, 3])
aa.shape

(7,)

In [68]:
a1=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1,4,5,6])
a1.shape

(12,)

In [69]:
a1.reshape(2,6)

array([[9, 8, 7, 6, 5, 4],
       [3, 2, 1, 4, 5, 6]])

In [70]:
a1.reshape(12,1)

array([[9],
       [8],
       [7],
       [6],
       [5],
       [4],
       [3],
       [2],
       [1],
       [4],
       [5],
       [6]])

In [71]:
a1.reshape(2,3,2)

array([[[9, 8],
        [7, 6],
        [5, 4]],

       [[3, 2],
        [1, 4],
        [5, 6]]])

In [72]:
#reshape into unknown dimension

a1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 4, 5, 6])

In [73]:
a1.reshape(2,1,-1)

array([[[9, 8, 7, 6, 5, 4]],

       [[3, 2, 1, 4, 5, 6]]])

In [74]:
a1.reshape(3,-1)

array([[9, 8, 7, 6],
       [5, 4, 3, 2],
       [1, 4, 5, 6]])

In [75]:
#iterating in array

for i in arr1:
    print(i)

2
3
4
5
6
7


In [81]:
arr3d

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]]])

In [77]:
for i in arr2d:
    print(i)
    

[1 2 3]
[4 5 6]


In [78]:
for i in arr2d:
    for j in i:
        print(j)

1
2
3
4
5
6


In [84]:
for i in a3d:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8
9


In [80]:
#nditer
for i in np.nditer(arr3d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [89]:
aa3=np.array([[3,4,5],[6,7,8],[1,2,3]])
aa3

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3]])

In [92]:
for i in aa3:
    for j in i:
        for k in j:
            print(k)

TypeError: 'numpy.int32' object is not iterable

In [91]:
#ndenumerate

for index, value in np.ndenumerate(arr3d):
    print(index, ':', value)

(0, 0, 0, 0) : 1
(0, 0, 0, 1) : 2
(0, 0, 0, 2) : 3
(0, 0, 1, 0) : 4
(0, 0, 1, 1) : 5
(0, 0, 1, 2) : 6
(0, 0, 2, 0) : 7
(0, 0, 2, 1) : 8
(0, 0, 2, 2) : 9
(0, 0, 3, 0) : 10
(0, 0, 3, 1) : 11
(0, 0, 3, 2) : 12


In [95]:
#concatenate

a1=np.array([[2,3,4],[22,33,44]])
a2=np.array([[5,6,7],[44,66,77]])
newarr=np.concatenate((a1,a2))
newarr

array([[ 2,  3,  4],
       [22, 33, 44],
       [ 5,  6,  7],
       [44, 66, 77]])

In [104]:
#axis =1
n2=np.concatenate((a1,a2), axis=1)

In [105]:
a1

array([[ 2,  3,  4],
       [22, 33, 44]])

In [106]:
a2

array([[ 5,  6,  7],
       [44, 66, 77]])

In [107]:
n2

array([[ 2,  3,  4,  5,  6,  7],
       [22, 33, 44, 44, 66, 77]])

In [10]:
#hstack
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.hstack((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

In [2]:
#vstack


In [11]:
#stack
np.dstack((arr1,arr2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [12]:
arr2d

NameError: name 'arr2d' is not defined

In [13]:
#searching in array
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.where(arr2d==2)

(array([0], dtype=int64), array([1], dtype=int64))

In [15]:
#search sorted

arr1=np.array([1,3,5,9,11])
x=np.searchsorted(arr1,7)

In [16]:
x

3

In [18]:
arr1=np.array([15,12,1,3,5,9,11])
x=np.searchsorted(arr1,8, side="left")
x

5

In [19]:
arr2d=np.array([[9,33,4],[44,5,3]])
arr2d

array([[ 9, 33,  4],
       [44,  5,  3]])

In [20]:
np.sort(arr2d)

array([[ 4,  9, 33],
       [ 3,  5, 44]])

In [21]:
#random

from numpy import random
x=random.rand(4)
x

array([0.28381284, 0.37969662, 0.08986279, 0.13668818])

In [22]:
x=random.randint(4)
x

1

In [24]:
x=random.randint(41, size=5)
x

array([12, 35, 40, 34, 14])

In [25]:
x=random.randint(41, size=(5,3))
x

array([[30, 24, 29],
       [ 9, 30, 30],
       [36, 33, 12],
       [13, 26, 12],
       [29, 39, 23]])

In [26]:
y=random.choice([2,4,6,8], size=(3,3))
y

array([[2, 4, 4],
       [4, 8, 6],
       [4, 8, 2]])